import BasicLayout from "@/components/Layout/BasicLayout";
import StyledComponentsRegistry from "@/lib/styledRegistry";
import { GlobalStyle } from "@/styles/GlobalStyle";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "TKIT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <BasicLayout>
                        <GlobalStyle />
                        {children}
                    </BasicLayout>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
