import BasicLayout from "@/components/Layout/BasicLayout";
import StyledComponentsRegistry from "@/lib/styledRegistry";
import { Pretendard } from "@/styles/Fonts";
import { GlobalStyle } from "@/styles/GlobalStyle";

export const metadata = {
    title: "TKIT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko" className={Pretendard.variable}>
            <body>
                <StyledComponentsRegistry>
                    <BasicLayout>
                        <GlobalStyle />
                        {children}
                    </BasicLayout>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
